### ISSUE TITLE
Add Microsoft's mctoll to front-ends.md

### ISSUE THREAD

**Issue by dzan** [decomp/decomp#216]
Seems like Microsoft has a lifter of their own;

https://github.com/Microsoft/llvm-mctoll

Might be interesting to add.

**Comment by mewmew** [comment]
Hi @dzan,

Thanks! The llvm-mctoll of Microsoft is definitely interesting.

The tool was added to https://github.com/decomp/decomp/blob/master/front-end.md#llvm-mctoll in rev 47e5832f8f0dfb686b33a45e500b451a5afb2d12 (and the typo of the repo URL was fixed in rev 18d871f22ba749f2de0dbf77a6e10962a35e3aac).

Cheers,
Robin
